version: '3.8'

services:
  web:
    build: .
    container_name: gem-hub-backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/.env:ro
    ports:
      - "5000:5000" # Keeps port 5000 bound strictly to the local host
    networks:
      - supabase_network
    volumes:
      - ./.env:/.env:ro

volumes:
  static_volume:

networks:
  supabase_network:
    external: true
    name: supabase_default  # Match the exact name from 'docker network ls'