# Generated by Django 6.0.3 on 2026-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_backup',
            field=models.BooleanField(default=False),
        ),
    ]
