name: Deploy to DigitalOcean

on:
  push:
    branches:
      - amila
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Server Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            set -e
            cd /opt/fileflow/Multi-Threaded-File-Transfer-System
            
            # Pull latest changes from your repo
            git pull origin main
            
            # Execute the deployment engine
            ./deploy/deploy.sh